[window]
decorations = "None"

[window.padding]
x = 10
y = 10

[font]
size = 11.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[cursor.style]
shape = "Beam"
blinking = "Always"


